# Define product data with categories
products = {
    "Sweets": [
        {"name": "Donuts", "price": 2.50, "image": "donuts.png"},
        {"name": "Chocolate Cake", "price": 3.00, "image": "chocolate cake.png"},
        {"name": "Brownie", "price": 2.75, "image": "brownie.png"},
        {"name": "Cupcake", "price": 2.90, "image": "cupcake.png"},
        {"name": "Macaron", "price": 3.20, "image": "macaron.png"},
        {"name": "Cookie", "price": 1.99, "image": "cookie.png"},
        {"name": "Pudding", "price": 2.60, "image": "pudding.png"},
        {"name": "Muffin", "price": 2.80, "image": "muffin.png"},
        {"name": "Strawberry Waffle", "price": 3.50, "image": "straw_waffle.png"},
        {"name": "Tart", "price": 3.10, "image": "tart.png"},
        {"name": "Ice Cream", "price": 3.00, "image": "icecream.png"},
        {"name": "Strawberry Farappuccino", "price": 2.20, "image": "strawberry_frap.png"},
    ],
    "Spicy": [
        {"name": "Burger", "price": 5.99, "image": "burger.png"},
        {"name": "Soup", "price": 2.99, "image": "soup.png"},
        {"name": "Noodles", "price": 6.50, "image": "noodles.png"},
        {"name": "Sushi", "price": 4.20, "image": "sushi.png"},
        {"name": "Biryani", "price": 4.99, "image": "biryani.png"},
        {"name": "Tacos", "price": 5.40, "image": "tacos.png"},
        {"name": "Tikka", "price": 6.20, "image": "tikka.png"},
        {"name": "Wrap", "price": 5.30, "image": "wrap.png"},
        {"name": "Nachos", "price": 4.75, "image": "nachos.png"},
        {"name": "Wings", "price": 5.80, "image": "wings.png"},
        {"name": "Kebab", "price": 6.00, "image": "kebab.png"},
        {"name": "Spicy Rice", "price": 4.99, "image": "spicyrice.png"},
    ],
    "Drinks": [
        {"name": "Coke", "price": 1.50, "image": "coke.png"},
        {"name": "Pepsi", "price": 1.50, "image": "pepsi.png"},
        {"name": "Orange Juice", "price": 2.00, "image": "orangejuice.png"},
        {"name": "Water", "price": 1.00, "image": "water.png"},
        {"name": "Milkshake", "price": 2.50, "image": "milkshake.png"},
        {"name": "Iced Tea", "price": 2.25, "image": "icedtea.png"},
        {"name": "Cappuccino", "price": 2.75, "image": "Cappuccino.png"},
        {"name": "Lemonade", "price": 2.10, "image": "lemonade.png"},
        {"name": "Smoothie", "price": 3.00, "image": "smoothie.png"},
        {"name": "Energy Drink", "price": 2.60, "image": "energydrink.png"},
        {"name": "Strawberry Shake", "price": 2.80, "image": "strawberryshake.png"},
        {"name": "Blueberry Cooler", "price": 2.90, "image": "blueberrycooler.png"},
    ]
}